apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJkbWwwWVV4cGJtRTRPVHBuYUhCZlkyTjNkMFV5U0VseU1WaEhObkpLWldZMVEyb3djblJQUVZoT1luRTBNbE5NVFZsQiIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson
